### ISSUE TITLE
Adjust schedule a demo button

### ISSUE THREAD

**Issue by mobiloudsupport** [mobiloudsupport/mobile-app#26]
When we first install the plugin we see a popup showing with a button that allows you to book a demo call.

Can we please perform the following adjustments on that popup:

1. The link to schedule a demo should open in a new browser tab
2. The buttons should be centered on the popup, right now they are aligned to the right

See here for reference: https://markuphero.com/share/lKhBuZvat78wCJsYsXMl

**Comment by Fiyerstorm** [comment]
Fixed in [21b0b75](https://github.com/mobiloudsupport/mobile-app/pull/27/commits/21b0b75669061d962b1eebd727875e64da776314)
