### ISSUE TITLE
Push notifications area not working

### ISSUE THREAD

**Issue by mobiloudsupport** [mobiloudsupport/mobile-app#29]
I have noticed that the push notifications area in the WP admin area of Media Trends is not working, the list of categories shows as "loading" but never finishes loading, see here: https://markuphero.com/share/j4SdV1LvJW8YrNTNmpNY

https://www.mediatrends.io/wp-admin/admin.php?page=canvas_push

The history also seems to be empty as if something was meant to be loaded there but couldn't.

Can you please check?

**Comment by Fiyerstorm** [comment]
Resolved in 222924bfd976450058851c11ed40e0c5fb1ecd0e
