### ISSUE TITLE
Automatic notification triggering when saving publish date

### ISSUE THREAD

**Issue by mobiloudsupport** [mobiloudsupport/mobile-app#8]
We have a problem with how automatic notifications work on Canvas, as they seem to be triggered when saving a publish date for the post.

To clarify, we are not publishing the post, we are simply scheduling a date for it to be published, and in this case the notification is being triggered, which should NOT happen.

Can we make sure the notification is only sent when a post is actually published?

**Comment by Fiyerstorm** [comment]
Fixed in 161b58c7454daa84b8a0916313e0bfae1d1bebb2
